export const UPDATE_USER = 'UPDATE_USER';

export const UPDATE_CURRENT_MESSAGE = 'UPDATE_CURRENT_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const REQUEST_MESSAGE_HISTORY = 'REQUEST_MESSAGE_HISTORY';
export const RECEIVE_MESSAGE_HISTORY = 'RECEIVE_MESSAGE_HISTORY';
